### ISSUE TITLE
Invalid SDP message not detected

### ISSUE THREAD

**Issue by alfonsoveneziano** [usnistgov/jsip#43]
Hi,
I'm experiencing an issue in case of an altered SDP message having:

- Content-Length: 0
- double \r\n at the message end
- strict set at true

In this scenario StringMsgParser method of the JSIP library does not detect a wrong message. Follows an example:

INVITE sip:mrwhite@10.101.5.120 SIP/2.0 
From: \"company\" <sip:company@10.101.6.120>;tag=35b8d8a74ca0f4e34e0adfa7_F10.101.6.120
To: sip:mrwhite@10.101.5.120
Call-ID: f_169eac17a017b0a4e0adfa8_I@10.101.6.120
CSeq: 15 INVITE
Via: SIP/2.0/UDP 10.101.6.120;branch=z9hG4bKf_169eac12baa17054e0adfb3_I
Content-Length: 0
Max-Forwards: 70
Contact: sip:company@10.101.6.120;transport=udp
Content-Type: application/sdp
User-Agent: SIP
Supported: replaces

v=0
o=sip:company@10.101.6.120 1 16 IN IP4 10.101.6.120
s=sip:company@10.101.6.120
c=IN IP4 10.101.6.120
t=0 0
m=audio 5000 RTP/AVP 0 8 18 4 120
a=rtpmap:0 PCMU/8000/1
a=rtpmap:8 PCMA/8000/1
a=rtpmap:18 G729/8000/1
a=fmtp:18 annexb=no
a=rtpmap:4 G723/8000/1
a=rtpmap:120 telephone-event/8000/1
"\r\n at the end"

Is there any setting to be done or is it a fault in the library?

The StringMsgParser code at the StringMsgParser.java

// Check for content legth header
    if (readBody && message.getContentLength() != null ) {
      if ( message.getContentLength().getContentLength() != 0) {
          int bodyLength = msgBuffer.length - i;

          byte[] body = new byte[bodyLength];
          System.arraycopy(msgBuffer, i, body, 0, bodyLength);
          message.setMessageContent(body,!strict,computeContentLengthFromMessage,message.getContentLength().getContentLength());
       } else if (!computeContentLengthFromMessage && message.getContentLength().getContentLength() == 0 & strict) {
           String last4Chars = new String(msgBuffer, msgBuffer.length - 4, 4);
           if(!"\r\n\r\n".equals(last4Chars)) {
               throw new ParseException("Extraneous characters at the end of the message ",i);
           }
       } 
does not detect the wrong message. 

Is there anything that must be set or is it a library fault? Thanks

**Comment by vladimirralev** [comment]
It's just the default choice in the library. There is no strict decision that the library can make in such case. The RFC says that the server must send an unspecified 400 class response in such case. Since the response code is application-specific, it makes sense to me that you should implement this behaviour in your specific app.

You can use the following setting to subclass `StringMsgParser`:

`gov.nist.javax.sip.MESSAGE_PARSER_FACTORY=com.company.CustomParserFactory`

Where the factory will produce `com.company.CustomParser` which inherits from `StringMsgParser` with the code at stake overriden in the way you like.

I can think of a few other ways to do this, but in any case it will have to be application decision how to behave in this case.

**Comment by alfonsoveneziano** [comment]
Ok, thanks for the reply.
